development:
  adapter: postgresql
  encoding: utf8
  database: gather_development
  pool: 5
  username: postgres

test:
  adapter: postgresql
  encoding: utf8
  database: gather_test
  pool: 5
  username: postgres

production:
  adapter: postgresql
  encoding: utf8
  database: gather_production
  pool: 5
  username: postgres
